---
title: Fhsd Nagel Journalist 1.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: The Official Nagel Website
description: A Middle School In Ohio
avatar: https://raw.githubusercontent.com/FHSD-Nagel-Journalist-1/FHSD-Nagel-Journalist-1.github.io/master/images/nagel-logo.png
navigation:
- name: Blog
  url: "/"
- name: About
  url: "/about"
- name: Archive
  url: "/archive"
- name: Tags
  url: "/tags"
- name: Theme
  url: https://github.com/FHSD-Nagel-Journalist-1/FHSD-Nagel-Journalist-1.github.io
paginate: 5
footer-links:
  behance: 
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: AWEEKJ/kiko-now
  googleplus: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  stackoverflow: 
  tumblr: 
  twitter: NagelNighthawks
  youtube: 
footer-text: "© 2018 Forest Hills"
disqus: nagel.disqus.com
google_analytics: 
url: 
baseurl: 
permalink: "/:title/"
paginate_path: "/page:num/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
